# Generated by Django 2.2.1 on 2019-06-13 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.CharField(max_length=10)),
                ('calloutDate', models.DateField(default=django.utils.timezone.now)),
                ('Uniformfield', models.TextField(default='')),
                ('Nonuniformfield', models.TextField(default='')),
            ],
        ),
    ]
